name: Actions Demo

# on: ["push"]
on:
  pull_request:
    branches: [main]

# permissions:
#   contents: read
#   actions: read
#   checks: write
#   pull-requests: write

jobs:
  test:
    # name: Codacy Coverage Reporter
    runs-on: ubuntu-latest
    # permissions:
    #   checks: write
    #   pull-requests: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
            distribution: 'corretto'
            java-version: '17'

      # - name: Run Unit Tests
      #   run: ./gradlew test

      - name: Run Build
        run: ./gradlew build

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: build/test-results/**/*.xml

      - name: Generate Kover Coverage Report
        run: ./gradlew koverXmlReport

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          # or
          # api-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: build/reports/kover/report.xml
          # or a comma-separated list for multiple reports
          # coverage-reports: <PATH_TO_REPORT>, <PATH_TO_REPORT>
